@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --no-genHtml`

import './test_test.dart' as test_test;
import 'package:test/test.dart';

void main() {
  test_test.main();
}