@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --no-genHtml`

import './lib/src/model/activity_test.dart' as lib_src_model_activity_test;
import './lib/src/model/emergencyContact_test.dart' as lib_src_model_emergencyContact_test;
import './lib/src/model/meal_test.dart' as lib_src_model_meal_test;
import './lib/src/model/user_test.dart' as lib_src_model_user_test;
import 'package:test/test.dart';

void main() {
  lib_src_model_activity_test.main();
  lib_src_model_emergencyContact_test.main();
  lib_src_model_meal_test.main();
  lib_src_model_user_test.main();
}
