language: node_js
cache: npm
node_js:
  - "11"
script:
  - npm run build
  - npm run test
  - npm run coverage

before_deploy:
  - "cd functions && npm install && cd .."

deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: "master"
