targets:
  $default:
    builders:
      built_redux|built_redux:
        enabled: true
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - --minify
            - --show-package-warnings

builders:
  built_redux:
    target: ":built_redux"
    import: "package:built_redux/builder.dart"
    builder_factories: ["builtRedux"]
    build_extensions: { ".dart": [".built_redux.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
