name: bsc
description: A web app for Belgrade Senior Center
version: 0.0.1
# homepage: https://www.msubot.com
authors: Spencer Cornish <spencerjcornish@gmail.com>

environment:
  sdk: "^2.1.0"

dependencies:
  build: ^1.1.0
  built_redux: ^7.5.2
  built_value: ^6.3.0
  firebase: ^5.0.2
  intl: ^0.15.7
  sentry_client: ^4.2.1
  stack_trace: ^1.9.3
  service_worker: ^0.2.3
  googleapis_auth: ^0.2.6
  wui_builder: ^0.7.1

dev_dependencies:
  test: ^1.5.3
  coverage:
  build_runner: ^1.2.3
  built_value_generator: ^6.3.0
  build_web_compilers: ^1.0.0
  sass: ^1.16.0

web:
  compiler:
    debug: dartdevc
